[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_rts = 0
monitor_dtr = 0
monitor_filters = esp32_exception_decoder
build_flags =
    -D ARDUINO_USB_MODE=1
    -D I2C_BUFFER_LENGTH=256
    -D SDFAT_FILE_TYPE=3
    -D SPI_DRIVER_SELECT=1
    -I ../shared/config
lib_deps =
    olikraus/U8g2
    bblanchon/ArduinoJson
    greiman/SdFat@^2.2.2
lib_extra_dirs =
    ../shared/libs
lib_ldf_mode = deep+