[env:mcu3]
platform   = espressif32 @ 6.10.0
framework  = espidf
board      = esp32dev

monitor_speed = 115200
upload_port   = /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
monitor_port  = /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0