[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
monitor_port = /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
monitor_rts = 0
monitor_dtr = 0
monitor_filters = esp32_exception_decoder
build_flags =
    -D I2C_BUFFER_LENGTH=256
    -I ../shared/config
lib_deps =
    olikraus/U8g2
    bblanchon/ArduinoJson
lib_extra_dirs =
    ../shared/libs
lib_ldf_mode = deep+